## hotkeys.yaml
hotkey-description-productiontypebuilding = Structures Tab
hotkey-description-productiontypesupport = Defences Tab
hotkey-description-productiontypeinfantry = Infantry Tab
hotkey-description-productiontypevehicle = Vehicles Tab
hotkey-description-productiontypeaircraft = Aircraft Tab
hotkey-description-productiontypenaval = Naval Tab
hotkey-description-productiontypetech = Upgrades Tab
hotkey-description-powerdown = Power-down mode
hotkey-description-decreasedepthpreviewcontrast = Decrease Contrast
hotkey-description-increasedepthpreviewcontrast = Increase Contrast
hotkey-description-decreasedepthpreviewoffset = Decrease Offset
hotkey-description-increasedepthpreviewoffset = Increase Offset
hotkey-description-toggledepthpreview = Toggle Preview
hotkey-description-cycleselectionsubgroup = Cycle Selection Subgroup
hotkey-description-cycleselectionsubgroupreverse = Cycle Selection Subgroup (Reverse)
hotkey-description-ordermove = Move
hotkey-description-orderattack = Attack
hotkey-description-orderattackground = Attack Ground
hotkey-description-orderstop = Stop
hotkey-description-orderscatter = Scatter
hotkey-description-orderstanceattackanything = Attack Anything Stance
hotkey-description-orderstancedefend = Defensive Stance
hotkey-description-orderstancereturnfire = Return Fire Stance
hotkey-description-orderstanceholdfire = Hold Fire Stance
hotkey-description-orderdeploy = Deploy
